
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_symp = OUTPUT_PATH / Path(r"C:\Users\Swamynathan\Documents\Vijay_Official\SIH\FrontEnd\build_symptoms\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH_symp / Path(path)


window = Tk()

window.geometry("480x320")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 320,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    240.0,
    160.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    240.0,
    55.0,
    image=image_image_2
)

canvas.create_text(
    70.0,
    40.0,
    anchor="nw",
    text="KIOSK Health Care Machine",
    fill="#3EF200",
    font=("Inter Bold", 25 * -1)
)

canvas.create_text(
    177.0,
    150.0,
    anchor="nw",
    text="Kindly Describe your symptoms ",
    fill="#30366E",
    font=("Inter Bold", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=105.0,
    y=135.0,
    width=50.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=314.0,
    y=238.0,
    width=132.0,
    height=35.0
)

canvas.create_text(
    326.0,
    246.0,
    anchor="nw",
    text="Book Appointment",
    fill="#3EF200",
    font=("Inter Bold", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
